/**
 * Defines a set of constants.
 */
const constants = {
  ENCRYPTIONS_KEYS: [],
  IDLE_SCREEN_WIDTH: 375,
  IDLE_SCREEN_HEIGHT: 812,
  XS_MAX_SCREEN_WIDTH: 414,
  XS_MAX_SCREEN_HEIGHT: 896,
  NETWORK_CONNECTION_ERROR: 408,
  USERS: [
    { id: 1, name: 'John Doe' },
    { id: 2, name: 'Jane Doe' },
    { id: 3, name: 'Jordan Doe' }
  ],

  FONT_VARIANTS: {
    TITLE_LARGE: { FONT_SIZE: 34, LINE_HEIGHT: 41, LETTER_SPACING: -0.4 },
    TITLE1: { FONT_SIZE: 28, LINE_HEIGHT: 34, LETTER_SPACING: -0.4 },
    TITLE2: { FONT_SIZE: 22, LINE_HEIGHT: 28, LETTER_SPACING: -0.4 },
    TITLE3: { FONT_SIZE: 20, LINE_HEIGHT: 25, LETTER_SPACING: -0.4 },
    HEADLINE: { FONT_SIZE: 17, LINE_HEIGHT: 22, LETTER_SPACING: -0.4 },
    BODY: { FONT_SIZE: 17, LINE_HEIGHT: 22, LETTER_SPACING: -0.4 },
    SUB_HEADLINE: { FONT_SIZE: 15, LINE_HEIGHT: 20, LETTER_SPACING: -0.4 },
    FOOTNOTE: { FONT_SIZE: 13, LINE_HEIGHT: 18, LETTER_SPACING: -0.4 },
    CAPTION1: { FONT_SIZE: 12, LINE_HEIGHT: 16, LETTER_SPACING: -0.4 },
    CAPTION2: { FONT_SIZE: 11, LINE_HEIGHT: 13, LETTER_SPACING: -0.4 }
  },
  FONT_FAMILY: {
    BOLD: 'BOLD',
    REGULAR: 'REGULAR'
  }
};

export default constants;
